In [1]:
import numpy as np
import csv
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

%pip install sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

Requirement already satisfied: sklearn in c:\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\anaconda3\lib\site-packages (from sklearn) (0.23.2)
Requirement already satisfied: numpy>=1.13.3 in c:\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.19.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.5.2)
Requirement already satisfied: joblib>=0.11 in c:\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

# 도서별 상세 정보(문화데이터)

### 문화데이터 불러오기 2019 - 202112
##### 원본데이터의 손실을 방지하기위해 하나씩 불러와서 합치자

#### 2019

In [98]:
book_2019 = pd.read_csv("datathon/NL_bo_species_master_new_2019.csv", low_memory = False, skiprows = [783400, 2002735])
book_2019 = book_2019.drop(['?master_seq', 'vol', 'author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url'], axis = 1)
book_2019 = book_2019.drop_duplicates(['description'])
book_2019.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1199652 entries, 0 to 3178394
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   isbn13       1199648 non-null  object
 1   title        1199650 non-null  object
 2   description  1199651 non-null  object
dtypes: object(3)
memory usage: 36.6+ MB

#### 202012-1

In [97]:
book_202012_1 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202012-1.csv", low_memory = False)
book_202012_1 = book_202012_1.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                  'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202012_1 = book_202012_1.drop_duplicates(['description'])
book_202012_1.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 479061 entries, 0 to 999427
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   isbn13         479061 non-null  object
 1   title          479061 non-null  object
 2   description    479060 non-null  object
 3   title_replace  479057 non-null  object
dtypes: object(4)
memory usage: 18.3+ MB

#### 202012-2

In [99]:
book_202012_2 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202012-2.csv", low_memory = False)
book_202012_2 = book_202012_2.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                                    'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202012_2 = book_202012_2.drop_duplicates(['description'])
book_202012_2.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 420753 entries, 0 to 991323
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   isbn13         420753 non-null  object
 1   title          420753 non-null  object
 2   description    420752 non-null  object
 3   title_replace  330670 non-null  object
dtypes: object(4)
memory usage: 16.1+ MB

#### 202012-3

In [100]:
book_202012_3 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202012-3.csv", low_memory = False)
book_202012_3 = book_202012_3.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202012_3 = book_202012_3.drop_duplicates(['description'])
book_202012_3.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208322 entries, 0 to 990346
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   isbn13         208322 non-null  object
 1   title          208322 non-null  object
 2   description    208321 non-null  object
 3   title_replace  200524 non-null  object
dtypes: object(4)
memory usage: 7.9+ MB

#### 202012-4

In [101]:
book_202012_4 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202012-4.csv", low_memory = False)
book_202012_4 = book_202012_4.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                 'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202012_4 = book_202012_4.drop_duplicates(['description'])
book_202012_4.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186588 entries, 0 to 464262
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   isbn13         186588 non-null  int64
 1   title          186588 non-null  object
 2   description    186587 non-null  object
 3   title_replace  184466 non-null  object
dtypes: int64(1), object(3)
memory usage: 7.1+ MB

#### 202012-5

In [102]:
book_202012_5 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202012-5.csv", low_memory = False)
book_202012_5 = book_202012_5.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                 'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202012_5 = book_202012_5.drop_duplicates(['description'])
book_202012_5.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11789 entries, 0 to 37582
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         11789 non-null  int64
 1   title          11789 non-null  object
 2   description    11788 non-null  object
 3   title_replace  11705 non-null  object
dtypes: int64(1), object(3)
memory usage: 460.5+ KB

#### 202101

In [103]:
book_202101 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202101.csv", low_memory = False)
book_202101 = book_202101.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                 'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202101 = book_202101.drop_duplicates(['description'])
book_202101.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4629 entries, 0 to 11050
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         4629 non-null   int64
 1   title          4629 non-null   object
 2   description    4628 non-null   object
 3   title_replace  4501 non-null   object
dtypes: int64(1), object(3)
memory usage: 180.8+ KB

#### 202102

In [104]:
book_202102 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202102.csv", low_memory = False)
book_202102 = book_202102.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202102 = book_202102.drop_duplicates(['description'])
book_202102.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 165733 entries, 0 to 448354
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   isbn13         165733 non-null  int64
 1   title          165733 non-null  object
 2   description    165732 non-null  object
 3   title_replace  165581 non-null  object
dtypes: int64(1), object(3)
memory usage: 6.3+ MB

#### 202103

In [105]:
book_202103 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202103.csv", low_memory = False)
book_202103 = book_202103.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202103 = book_202103.drop_duplicates(['description'])
book_202103.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9063 entries, 0 to 26666
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         9063 non-null   int64
 1   title          9063 non-null   object
 2   description    9062 non-null   object
 3   title_replace  8902 non-null   object
dtypes: int64(1), object(3)
memory usage: 354.0+ KB

#### 202104

In [106]:
book_202104 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202104.csv", low_memory = False)
book_202104 = book_202104.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202104 = book_202104.drop_duplicates(['description'])
book_202104.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16481 entries, 0 to 33433
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         16481 non-null  int64
 1   title          16481 non-null  object
 2   description    16480 non-null  object
 3   title_replace  16016 non-null  object
dtypes: int64(1), object(3)
memory usage: 643.8+ KB

#### 202105

In [107]:
book_202105 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202105.csv", low_memory = False)
book_202105 = book_202105.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202105 = book_202105.drop_duplicates(['description'])
book_202105.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15631 entries, 0 to 34328
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         15631 non-null  int64
 1   title          15631 non-null  object
 2   description    15630 non-null  object
 3   title_replace  15112 non-null  object
dtypes: int64(1), object(3)
memory usage: 610.6+ KB

#### 202106

In [108]:
book_202106 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202106.csv", low_memory = False)
book_202106 = book_202106.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202106 = book_202106.drop_duplicates(['description'])
book_202106.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24776 entries, 0 to 71652
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         24776 non-null  int64
 1   title          24776 non-null  object
 2   description    24775 non-null  object
 3   title_replace  24120 non-null  object
dtypes: int64(1), object(3)
memory usage: 967.8+ KB

#### 202107

In [109]:
book_202107 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202107.csv", low_memory = False)
book_202107 = book_202107.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202107 = book_202107.drop_duplicates(['description'])
book_202107.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7292 entries, 0 to 23797
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         7292 non-null   int64
 1   title          7292 non-null   object
 2   description    7291 non-null   object
 3   title_replace  6669 non-null   object
dtypes: int64(1), object(3)
memory usage: 284.8+ KB

#### 202108

In [110]:
book_202108 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202108.csv", low_memory = False)
book_202108 = book_202108.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202108 = book_202108.drop_duplicates(['description'])
book_202108.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31817 entries, 0 to 64246
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         31817 non-null  int64
 1   title          31817 non-null  object
 2   description    31816 non-null  object
 3   title_replace  31330 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.2+ MB

#### 202109

In [111]:
book_202109 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202109.csv", low_memory = False)
book_202109 = book_202109.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202109 = book_202109.drop_duplicates(['description'])
book_202109.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29966 entries, 0 to 267579
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         29966 non-null  int64
 1   title          29966 non-null  object
 2   description    29965 non-null  object
 3   title_replace  29130 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.1+ MB

#### 202110

In [112]:
book_202110 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202110.csv", low_memory = False)
book_202110 = book_202110.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202110 = book_202110.drop_duplicates(['description'])
book_202110.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6875 entries, 0 to 16836
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         6875 non-null   int64
 1   title          6875 non-null   object
 2   description    6874 non-null   object
 3   title_replace  6329 non-null   object
dtypes: int64(1), object(3)
memory usage: 268.6+ KB

#### 202111

In [113]:
book_202111 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202111.csv", low_memory = False)
book_202111 = book_202111.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202111 = book_202111.drop_duplicates(['description'])
book_202111.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46311 entries, 0 to 102818
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         46311 non-null  int64
 1   title          46311 non-null  object
 2   description    46310 non-null  object
 3   title_replace  45465 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.8+ MB

#### 202112

In [114]:
book_202112 = pd.read_csv("datathon/NL_BO_SPECIES_MASTER_NEW_202112.csv", low_memory = False)
book_202112 = book_202112.drop(['author', 'publisher', 'pub_date', 'add_code', 'price', 'img_url', 'kdc_class_no', 
                'master_seq', 'vol', 'isbn_origin', 'author_replace', 'pub_date_2', 'is_coll_aladin', 'is_coll_naver'], axis = 1)
book_202112 = book_202112.drop_duplicates(['description'])
book_202112.info()
# 문화데이터 불러와서 description에 중복되는 내용 및 결측치 제거

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74338 entries, 0 to 157111
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   isbn13         74338 non-null  int64
 1   title          74338 non-null  object
 2   description    74337 non-null  object
 3   title_replace  73119 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.8+ MB

## 불러온 문화데이터 합치기

##### 모든 문화데이터를 concat()한 book생성

In [245]:
book = pd.concat([book_2019, book_202012_1, book_202012_2, book_202012_3, book_202012_4, book_202012_5, book_202101, book_202102,
                  book_202103, book_202104, book_202105, book_202106, book_202107, book_202108, book_202109, book_202110, 
                  book_202111, book_202112])
book = book.drop_duplicates(['description'])
book = book.drop_duplicates(['title']) 
book = book.drop_duplicates(['isbn13']) 
# 중복되는 row 삭제
book = book.dropna(subset = ['description'])
book = book.dropna(subset = ['title'])
book = book.dropna(subset = ['isbn13'])
# NAN값 제거
book = book.reset_index(drop=True)
# index 오름차순 재배열
book = book.drop(['title_replace'], axis = 1)
# 불필요해 보이는 title_replace 삭제
book

,isbn13,title,description
0,9788953278974,신곡주계 폴리포니카,신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 신곡 악사의 이야기....
1,9788953283589,아수라 크라잉 =Asura cryin',라쿠로와 고등학교에서 도난 사건이 발생했다.&#x0D;범인은「하멜른의 속옷남」이라는...
2,9788974572549,(English) fantasy,"국내에서 기획 제작한 어린이용 영어 팬터지. 간결한 문장, 사전을 찾지 않아도 될 ..."
3,9788926325117,제로의 사역마,"'역시 난 사이토를 좋아하나 봐.' '보이는 거, 그렇게 싫지 않았어.' '난 몹쓸..."
4,9788953283459,디어 왈츠 =Dear waltz,투덜이 미소년 강세겸은 요즘 헷갈려하는 중이다. 미향이를 보며 가슴이 뛰는 건 연애...
...,...,...,...
1244545,9791197569708,우리 없는 세상,작가는 사회복지사와 상담가로 오래 일했다. 그는 자살로 누군가를 잃었거나 스스로 자...
1244546,9791138804486,위대한 영혼의 미소,재외 작가의 장편소설. 인고와 눈물로 점철된 코리안 뉴요커들의 이민 역정을 다룬 이...
1244547,9791138804523,"잊지 말자, 나는 기적이라는 걸 - 늘 그랬던 것처럼, 신발 끈을 고쳐 맬 우리",갑작스레 세상에 나 혼자 남겨진 느낌이 들 때가 있다. 주위가 암전되고 덩그러니 남...
1244548,9791197549335,전념 - 나와 세상을 바꾸는 힘에 관하여,오랫동안 하나의 목적을 이루기 위해 전념한 다양한 영웅들의 사례도 제시하고 있다. ...
1244549,9788970936222,2022 예산회계실무 기본서 - 지방자치단체 및 공공기관의,"지방자치단체와 공공기관(공기업, 출자ㆍ출연기관, 민간위탁, 보조단체 포함)에서 회계..."

In [147]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1244550 entries, 0 to 1244549
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   isbn13       1244550 non-null  object
 1   title        1244550 non-null  object
 2   description  1244550 non-null  object
dtypes: object(3)
memory usage: 28.5+ MB

#####  title과 description을 하나의 컬럼으로 합친 새로운 column 'overview' 생성.. 컨텐츠(줄거리) 기반의 필터링 실시에 있어서 정확도 향상을 위하여(주요 키워드 빈도수 향상을 위해)

In [246]:
cols = ['title', 'description']
book['overview'] = book[cols].apply(lambda row : ' '.join(row.values.astype(str)), axis = 1)
# title과 description을 합치는데에 있어서 TfidfVectorizer을 위해 한 칸 띄어서 합치기
book

,isbn13,title,description,overview
0,9788953278974,신곡주계 폴리포니카,신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 신곡 악사의 이야기....,신곡주계 폴리포니카 신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 ...
1,9788953283589,아수라 크라잉 =Asura cryin',라쿠로와 고등학교에서 도난 사건이 발생했다.&#x0D;범인은「하멜른의 속옷남」이라는...,아수라 크라잉 =Asura cryin' 라쿠로와 고등학교에서 도난 사건이 발생했다....
2,9788974572549,(English) fantasy,"국내에서 기획 제작한 어린이용 영어 팬터지. 간결한 문장, 사전을 찾지 않아도 될 ...",(English) fantasy 국내에서 기획 제작한 어린이용 영어 팬터지. 간결한...
3,9788926325117,제로의 사역마,"'역시 난 사이토를 좋아하나 봐.' '보이는 거, 그렇게 싫지 않았어.' '난 몹쓸...","제로의 사역마 '역시 난 사이토를 좋아하나 봐.' '보이는 거, 그렇게 싫지 않았..."
4,9788953283459,디어 왈츠 =Dear waltz,투덜이 미소년 강세겸은 요즘 헷갈려하는 중이다. 미향이를 보며 가슴이 뛰는 건 연애...,디어 왈츠 =Dear waltz 투덜이 미소년 강세겸은 요즘 헷갈려하는 중이다. 미...
...,...,...,...,...
1244545,9791197569708,우리 없는 세상,작가는 사회복지사와 상담가로 오래 일했다. 그는 자살로 누군가를 잃었거나 스스로 자...,우리 없는 세상 작가는 사회복지사와 상담가로 오래 일했다. 그는 자살로 누군가를 잃...
1244546,9791138804486,위대한 영혼의 미소,재외 작가의 장편소설. 인고와 눈물로 점철된 코리안 뉴요커들의 이민 역정을 다룬 이...,위대한 영혼의 미소 재외 작가의 장편소설. 인고와 눈물로 점철된 코리안 뉴요커들의 ...
1244547,9791138804523,"잊지 말자, 나는 기적이라는 걸 - 늘 그랬던 것처럼, 신발 끈을 고쳐 맬 우리",갑작스레 세상에 나 혼자 남겨진 느낌이 들 때가 있다. 주위가 암전되고 덩그러니 남...,"잊지 말자, 나는 기적이라는 걸 - 늘 그랬던 것처럼, 신발 끈을 고쳐 맬 우리 갑..."
1244548,9791197549335,전념 - 나와 세상을 바꾸는 힘에 관하여,오랫동안 하나의 목적을 이루기 위해 전념한 다양한 영웅들의 사례도 제시하고 있다. ...,전념 - 나와 세상을 바꾸는 힘에 관하여 오랫동안 하나의 목적을 이루기 위해 전념한...
1244549,9788970936222,2022 예산회계실무 기본서 - 지방자치단체 및 공공기관의,"지방자치단체와 공공기관(공기업, 출자ㆍ출연기관, 민간위탁, 보조단체 포함)에서 회계...",2022 예산회계실무 기본서 - 지방자치단체 및 공공기관의 지방자치단체와 공공기관(...

In [154]:
book['overview'].head()

0    신곡주계 폴리포니카 신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 ...
1    아수라 크라잉 =Asura cryin' 라쿠로와 고등학교에서 도난 사건이 발생했다....
2    (English) fantasy 국내에서 기획 제작한 어린이용 영어 팬터지. 간결한...
3    제로의 사역마  '역시 난 사이토를 좋아하나 봐.' '보이는 거, 그렇게 싫지 않았...
4    디어 왈츠 =Dear waltz 투덜이 미소년 강세겸은 요즘 헷갈려하는 중이다. 미...
Name: overview, dtype: object

In [247]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1244550 entries, 0 to 1244549
Data columns (total 4 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   isbn13       1244550 non-null  object
 1   title        1244550 non-null  object
 2   description  1244550 non-null  object
 3   overview     1244550 non-null  object
dtypes: object(4)
memory usage: 38.0+ MB

In [156]:
book['overview'].isnull().values.any()
# description column에 결측치 없는 것 확인
# 앞의 전처리과정에서 결측지 모두 제거함

False

##### 1. overview의 영어와 한글을 제외한 특수문자 및 숫자등은 모두 삭제

In [248]:
import re
book['overview'] = [re.sub(r'\d+', '', s) for s in book['overview']]
book['overview'] = [re.sub(r'[^\w\s]', '', s) for s in book['overview']]
book['overview'].tail()

1244545    우리 없는 세상 작가는 사회복지사와 상담가로 오래 일했다 그는 자살로 누군가를 잃었...
1244546    위대한 영혼의 미소 재외 작가의 장편소설 인고와 눈물로 점철된 코리안 뉴요커들의 이...
1244547    잊지 말자 나는 기적이라는 걸  늘 그랬던 것처럼 신발 끈을 고쳐 맬 우리 갑작스레...
1244548    전념  나와 세상을 바꾸는 힘에 관하여 오랫동안 하나의 목적을 이루기 위해 전념한 ...
1244549     예산회계실무 기본서  지방자치단체 및 공공기관의 지방자치단체와 공공기관공기업 출자...
Name: overview, dtype: object

##### 2. 영어와 한글 불용어 사전을 이용해서 불필요한 조사 및 관사 삭제

##### 영어 불용어 사전

In [162]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_eng = TfidfVectorizer(stop_words = 'english')
# 영어의 경우 불용어사전이 scikit-learn 라이브러리에 있으므로 이용하자 (한글의 경우 없으므로 만들어줘야됨)
# tfidf_eng = 영어의 불필요한 관사등을 제거하기 위한 객체

In [163]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
ENGLISH_STOP_WORDS
# 영어 불용어 사전에는 어떤게 있는지

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

##### 한글 불용어 사전

In [206]:
with open("datathon/한글 불용어 사전.txt", 'r', encoding = "utf-8") as f:
  list_file = f.readlines() 
stopwords_kor = [l.strip() for l in list_file]
# stopwords_kor = list_file[0].split(",")
# 한글 불용어들을 작성한 텍스트파일(이하 한글 불용어 사전) 불러오기

In [207]:
stopwords_kor
# 한국 불용어 사전에는 어떤게 있는지

['아',
 '휴',
 '아이구',
 '아이쿠',
 '아이고',
 '어',
 '나',
 '우리',
 '저희',
 '따라',
 '의해',
 '을',
 '를',
 '에',
 '의',
 '가',
 '으로',
 '로',
 '에게',
 '뿐이다',
 '의거하여',
 '근거하여',
 '입각하여',
 '기준으로',
 '예하면',
 '예를 들면',
 '예를 들자면',
 '저',
 '소인',
 '소생',
 '저희',
 '지말고',
 '하지마',
 '하지마라',
 '다른',
 '물론',
 '또한',
 '그리고',
 '비길수 없다',
 '해서는 안된다',
 '뿐만 아니라',
 '만이 아니다',
 '만은 아니다',
 '막론하고',
 '관계없이',
 '그치지 않다',
 '그러나',
 '그런데',
 '하지만',
 '든간에',
 '논하지 않다',
 '따지지 않다',
 '설사',
 '비록',
 '더라도',
 '아니면',
 '만 못하다',
 '하는 편이 낫다',
 '불문하고',
 '향하여',
 '향해서',
 '향하다',
 '쪽으로',
 '틈타',
 '이용하여',
 '타다',
 '오르다',
 '제외하고',
 '이 외에',
 '이 밖에',
 '하여야',
 '비로소',
 '한다면 몰라도',
 '외에도',
 '이곳',
 '여기',
 '부터',
 '기점으로',
 '따라서',
 '할 생각이다',
 '하려고하다',
 '이리하여',
 '그리하여',
 '그렇게 함으로써',
 '하지만',
 '일때',
 '할때',
 '앞에서',
 '중에서',
 '보는데서',
 '으로써',
 '로써',
 '까지',
 '해야한다',
 '일것이다',
 '반드시',
 '할줄알다',
 '할수있다',
 '할수있어',
 '임에 틀림없다',
 '한다면',
 '등',
 '등등',
 '제',
 '겨우',
 '단지',
 '다만',
 '할뿐',
 '딩동',
 '댕그',
 '대해서',
 '대하여',
 '대하면',
 '훨씬',
 '얼마나',
 '얼마만큼',
 '얼마큼',
 '남짓',
 '여',
 '얼마간',
 '약간',
 '다소',
 '좀',
 '조금',
 '다수',
 '몇',
 '얼마',
 '지만',
 '하물며',
 '또한',
 '그러나',
 '그렇지만',
 '하지만',
 '이외에도',
 '대해 말하자면',
 '뿐이다',
 '다음에',
 '반대로',
 '반대로 말하자면',
 '이와 반대로',
 '바꾸어서 말하면',
 '바꾸어서 한다면',
 '만약',
 '그렇지않으면',
 '까악',
 '툭',
 '딱',
 '삐걱거리다',
 '보드득',
 '비걱거리다',
 '꽈당',
 '응당',
 '해야한다',
 '에 가서',
 '각',
 '각각',
 '여러분',
 '각종',
 '각자',
 '제각기',
 '하도록하다',
 '와',
 '과',
 '그러므로',
 '그래서',
 '고로',
 '한 까닭에',
 '하기 때문에',
 '거니와',
 '이지만',
 '대하여',
 '관하여',
 '관한',
 '과연',
 '실로',
 '아니나다를가',
 '생각한대로',
 '진짜로',
 '한적이있다',
 '하곤하였다',
 '하',
 '하하',
 '허허',
 '아하',
 '거바',
 '와',
 '오',
 '왜',
 '어째서',
 '무엇때문에',
 '어찌',
 '하겠는가',
 '무슨',
 '어디',
 '어느곳',
 '더군다나',
 '하물며',
 '더욱이는',
 '어느때',
 '언제',
 '야',
 '이봐',
 '어이',
 '여보시오',
 '흐흐',
 '흥',
 '휴',
 '헉헉',
 '헐떡헐떡',
 '영차',
 '여차',
 '어기여차',
 '끙끙',
 '아야',
 '앗',
 '아야',
 '콸콸',
 '졸졸',
 '좍좍',
 '뚝뚝',
 '주룩주룩',
 '솨',
 '우르르',
 '그래도',
 '또',
 '그리고',
 '바꾸어말하면',
 '바꾸어말하자면',
 '혹은',
 '혹시',
 '답다',
 '및',
 '그에 따르는',
 '때가 되어',
 '즉',
 '지든지',
 '설령',
 '가령',
 '하더라도',
 '할지라도',
 '일지라도',
 '지든지',
 '몇',
 '거의',
 '하마터면',
 '인젠',
 '이젠',
 '된바에야',
 '된이상',
 '만큼\t어찌됏든',
 '그위에',
 '게다가',
 '점에서 보아',
 '비추어 보아',
 '고려하면',
 '하게될것이다',
 '일것이다',
 '비교적',
 '좀',
 '보다더',
 '비하면',
 '시키다',
 '하게하다',
 '할만하다',
 '의해서',
 '연이서',
 '이어서',
 '잇따라',
 '뒤따라',
 '뒤이어',
 '결국',
 '의지하여',
 '기대여',
 '통하여',
 '자마자',
 '더욱더',
 '불구하고',
 '얼마든지',
 '마음대로',
 '주저하지 않고',
 '곧',
 '즉시',
 '바로',
 '당장',
 '하자마자',
 '밖에 안된다',
 '하면된다',
 '그래',
 '그렇지',
 '요컨대',
 '다시 말하자면',
 '바꿔 말하면',
 '즉',
 '구체적으로',
 '말하자면',
 '시작하여',
 '시초에',
 '이상',
 '허',
 '헉',
 '허걱',
 '바와같이',
 '해도좋다',
 '해도된다',
 '게다가',
 '더구나',
 '하물며',
 '와르르',
 '팍',
 '퍽',
 '펄렁',
 '동안',
 '이래',
 '하고있었다',
 '이었다',
 '에서',
 '로부터',
 '까지',
 '예하면',
 '했어요',
 '해요',
 '함께',
 '같이',
 '더불어',
 '마저',
 '마저도',
 '양자',
 '모두',
 '습니다',
 '가까스로',
 '하려고하다',
 '즈음하여',
 '다른',
 '다른 방면으로',
 '해봐요',
 '습니까',
 '했어요',
 '말할것도 없고',
 '무릎쓰고',
 '개의치않고',
 '하는것만 못하다',
 '하는것이 낫다',
 '매',
 '매번',
 '들',
 '모',
 '어느것',
 '어느',
 '로써',
 '갖고말하자면',
 '어디',
 '어느쪽',
 '어느것',
 '어느해',
 '어느 년도',
 '라 해도',
 '언젠가',
 '어떤것',
 '어느것',
 '저기',
 '저쪽',
 '저것',
 '그때',
 '그럼',
 '그러면',
 '요만한걸',
 '그래',
 '그때',
 '저것만큼',
 '그저',
 '이르기까지',
 '할 줄 안다',
 '할 힘이 있다',
 '너',
 '너희',
 '당신',
 '어찌',
 '설마',
 '차라리',
 '할지언정',
 '할지라도',
 '할망정',
 '할지언정',
 '구토하다',
 '게우다',
 '토하다',
 '메쓰겁다',
 '옆사람',
 '퉤',
 '쳇',
 '의거하여',
 '근거하여',
 '의해',
 '따라',
 '힘입어',
 '그',
 '다음',
 '버금',
 '두번째로',
 '기타',
 '첫번째로',
 '나머지는',
 '그중에서',
 '견지에서',
 '형식으로 쓰여',
 '입장에서',
 '위해서',
 '단지',
 '의해되다',
 '하도록시키다',
 '뿐만아니라',
 '반대로',
 '전후',
 '전자',
 '앞의것',
 '잠시',
 '잠깐',
 '하면서',
 '그렇지만',
 '다음에',
 '그러한즉',
 '그런즉',
 '남들',
 '아무거나',
 '어찌하든지',
 '같다',
 '비슷하다',
 '예컨대',
 '이럴정도로',
 '어떻게',
 '만약',
 '만일',
 '위에서 서술한바와같이',
 '인 듯하다',
 '하지 않는다면',
 '만약에',
 '무엇',
 '무슨',
 '어느',
 '어떤',
 '아래윗',
 '조차',
 '한데',
 '그럼에도 불구하고',
 '여전히',
 '심지어',
 '까지도',
 '조차도',
 '하지 않도록',
 '않기 위하여',
 '때',
 '시각',
 '무렵',
 '시간',
 '동안',
 '어때',
 '어떠한',
 '하여금',
 '네',
 '예',
 '우선',
 '누구',
 '누가 알겠는가',
 '아무도',
 '줄은모른다',
 '줄은 몰랏다',
 '하는 김에',
 '겸사겸사',
 '하는바',
 '그런 까닭에',
 '한 이유는',
 '그러니',
 '그러니까',
 '때문에',
 '그',
 '너희',
 '그들',
 '너희들',
 '타인',
 '것',
 '것들',
 '너',
 '위하여',
 '공동으로',
 '동시에',
 '하기 위하여',
 '어찌하여',
 '무엇때문에',
 '붕붕',
 '윙윙',
 '나',
 '우리',
 '엉엉',
 '휘익',
 '윙윙',
 '오호',
 '아하',
 '어쨋든',
 '만 못하다\t하기보다는',
 '차라리',
 '하는 편이 낫다',
 '흐흐',
 '놀라다',
 '상대적으로 말하자면',
 '마치',
 '아니라면',
 '쉿',
 '그렇지 않으면',
 '그렇지 않다면',
 '안 그러면',
 '아니었다면',
 '하든지',
 '아니면',
 '이라면',
 '좋아',
 '알았어',
 '하는것도',
 '그만이다',
 '어쩔수 없다',
 '하나',
 '일',
 '일반적으로',
 '일단',
 '한켠으로는',
 '오자마자',
 '이렇게되면',
 '이와같다면',
 '전부',
 '한마디',
 '한항목',
 '근거로',
 '하기에',
 '아울러',
 '하지 않도록',
 '않기 위해서',
 '이르기까지',
 '이 되다',
 '로 인하여',
 '까닭으로',
 '이유만으로',
 '이로 인하여',
 '그래서',
 '이 때문에',
 '그러므로',
 '그런 까닭에',
 '알 수 있다',
 '결론을 낼 수 있다',
 '으로 인하여',
 '있다',
 '어떤것',
 '관계가 있다',
 '관련이 있다',
 '연관되다',
 '어떤것들',
 '에 대해',
 '이리하여',
 '그리하여',
 '여부',
 '하기보다는',
 '하느니',
 '하면 할수록',
 '운운',
 '이러이러하다',
 '하구나',
 '하도다',
 '다시말하면',
 '다음으로',
 '에 있다',
 '에 달려 있다',
 '우리',
 '우리들',
 '오히려',
 '하기는한데',
 '어떻게',
 '어떻해',
 '어찌됏어',
 '어때',
 '어째서',
 '본대로',
 '자',
 '이',
 '이쪽',
 '여기',
 '이것',
 '이번',
 '이렇게말하자면',
 '이런',
 '이러한',
 '이와 같은',
 '요만큼',
 '요만한 것',
 '얼마 안 되는 것',
 '이만큼',
 '이 정도의',
 '이렇게 많은 것',
 '이와 같다',
 '이때',
 '이렇구나',
 '것과 같이',
 '끼익',
 '삐걱',
 '따위',
 '와 같은 사람들',
 '부류의 사람들',
 '왜냐하면',
 '중의하나',
 '오직',
 '오로지',
 '에 한하다',
 '하기만 하면',
 '도착하다',
 '까지 미치다',
 '도달하다',
 '정도에 이르다',
 '할 지경이다',
 '결과에 이르다',
 '관해서는',
 '여러분',
 '하고 있다',
 '한 후',
 '혼자',
 '자기',
 '자기집',
 '자신',
 '우에 종합한것과같이',
 '총적으로 보면',
 '총적으로 말하면',
 '총적으로',
 '대로 하다',
 '으로서',
 '참',
 '그만이다',
 '할 따름이다',
 '쿵',
 '탕탕',
 '쾅쾅',
 '둥둥',
 '봐',
 '봐라',
 '아이야',
 '아니',
 '와아',
 '응',
 '아이',
 '참나',
 '년',
 '월',
 '일',
 '령',
 '영',
 '일',
 '이',
 '삼',
 '사',
 '오',
 '육',
 '륙',
 '칠',
 '팔',
 '구',
 '이천육',
 '이천칠',
 '이천팔',
 '이천구',
 '하나',
 '둘',
 '셋',
 '넷',
 '다섯',
 '여섯',
 '일곱',
 '여덟',
 '아홉',
 '령',
 '영',
 '가',
 '가까스로',
 '가령',
 '각',
 '각각',
 '각자',
 '각종',
 '갖고말하자면',
 '같다',
 '같이',
 '개의치않고',
 '거니와',
 '거바',
 '거의',
 '것',
 '것과 같이',
 '것들',
 '게다가',
 '게우다',
 '겨우',
 '견지에서',
 '결과에 이르다',
 '결국',
 '결론을 낼 수 있다',
 '겸사겸사',
 '고려하면',
 '고로',
 '곧',
 '공동으로',
 '과',
 '과연',
 '관계가 있다',
 '관계없이',
 '관련이 있다',
 '관하여',
 '관한',
 '관해서는',
 '구',
 '구체적으로',
 '구토하다',
 '그',
 '그들',
 '그때',
 '그래',
 '그래도',
 '그래서',
 '그러나',
 '그러니',
 '그러니까',
 '그러면',
 '그러므로',
 '그러한즉',
 '그런 까닭에',
 '그런데',
 '그런즉',
 '그럼',
 '그럼에도 불구하고',
 '그렇게 함으로써',
 '그렇지',
 '그렇지 않다면',
 '그렇지 않으면',
 '그렇지만',
 '그렇지않으면',
 '그리고',
 '그리하여',
 '그만이다',
 '그에 따르는',
 '그위에',
 '그저',
 '그중에서',
 '그치지 않다',
 '근거로',
 '근거하여',
 '기대여',
 '기점으로',
 '기준으로',
 '기타',
 '까닭으로',
 '까악',
 '까지',
 '까지 미치다',
 '까지도',
 '꽈당',
 '끙끙',
 '끼익',
 '나',
 '나머지는',
 '남들',
 '남짓',
 '너',
 '너희',
 '너희들',
 '네',
 '넷',
 '년',
 '논하지 않다',
 '놀라다',
 '누가 알겠는가',
 '누구',
 '다른',
 '다른 방면으로',
 '다만',
 '다섯',
 '다소',
 '다수',
 '다시 말하자면',
 '다시말하면',
 '다음',
 '다음에',
 '다음으로',
 '단지',
 '답다',
 '당신',
 '당장',
 '대로 하다',
 '대하면',
 '대하여',
 '대해 말하자면',
 '대해서',
 '댕그',
 '더구나',
 '더군다나',
 '더라도',
 '더불어',
 '더욱더',
 '더욱이는',
 '도달하다',
 '도착하다',
 '동시에',
 '동안',
 '된바에야',
 '된이상',
 '두번째로',
 '둘',
 '둥둥',
 '뒤따라',
 '뒤이어',
 '든간에',
 '들',
 '등',
 '등등',
 '딩동',
 '따라',
 '따라서',
 '따위',
 '따지지 않다',
 '딱',
 '때',
 '때가 되어',
 '때문에',
 '또',
 '또한',
 '뚝뚝',
 '라 해도',
 '령',
 '로',
 '로 인하여',
 '로부터',
 '로써',
 '륙',
 '를',
 '마음대로',
 '마저',
 '마저도',
 '마치',
 '막론하고',
 '만 못하다',
 '만약',
 '만약에',
 '만은 아니다',
 '만이 아니다',
 '만일',
 '만큼',
 '말하자면',
 '말할것도 없고',
 '매',
 '매번',
 '메쓰겁다',
 '몇',
 '모',
 '모두',
 '무렵',
 '무릎쓰고',
 '무슨',
 '무엇',
 '무엇때문에',
 '물론',
 '및',
 '바꾸어말하면',
 '바꾸어말하자면',
 '바꾸어서 말하면',
 '바꾸어서 한다면',
 '바꿔 말하면',
 '바로',
 '바와같이',
 '밖에 안된다',
 '반대로',
 '반대로 말하자면',
 '반드시',
 '버금',
 '보는데서',
 '보다더',
 '보드득',
 '본대로',
 '봐',
 '봐라',
 '부류의 사람들',
 '부터',
 '불구하고',
 '불문하고',
 '붕붕',
 '비걱거리다',
 '비교적',
 '비길수 없다',
 '비로소',
 '비록',
 '비슷하다',
 '비추어 보아',
 '비하면',
 '뿐만 아니라',
 '뿐만아니라',
 '뿐이다',
 '삐걱',
 '삐걱거리다',
 '사',
 '삼',
 '상대적으로 말하자면',
 '생각한대로',
 '설령',
 '설마',
 '설사',
 '셋',
 '소생',
 '소인',
 '솨',
 '쉿',
 '습니까',
 '습니다',
 '시각',
 '시간',
 '시작하여',
 '시초에',
 '시키다',
 '실로',
 '심지어',
 '아',
 '아니',
 '아니나다를가',
 '아니라면',
 '아니면',
 '아니었다면',
 '아래윗',
 '아무거나',
 '아무도',
 '아야',
 '아울러',
 '아이',
 '아이고',
 '아이구',
 '아이야',
 '아이쿠',
 '아하',
 '아홉',
 '안 그러면',
 '않기 위하여',
 '않기 위해서',
 '알 수 있다',
 '알았어',
 '앗',
 '앞에서',
 '앞의것',
 '야',
 '약간',
 '양자',
 '어',
 '어기여차',
 '어느',
 '어느 년도',
 '어느것',
 '어느곳',
 '어느때',
 '어느쪽',
 '어느해',
 '어디',
 '어때',
 '어떠한',
 '어떤',
 '어떤것',
 '어떤것들',
 '어떻게',
 '어떻해',
 '어이',
 '어째서',
 '어쨋든',
 '어쩔수 없다',
 '어찌',
 '어찌됏든',
 '어찌됏어',
 '어찌하든지',
 '어찌하여',
 '언제',
 '언젠가',
 '얼마',
 '얼마 안 되는 것',
 '얼마간',
 '얼마나',
 '얼마든지',
 '얼마만큼',
 '얼마큼',
 '엉엉',
 '에',
 '에 가서',
 '에 달려 있다',
 '에 대해',
 '에 있다',
 '에 한하다',
 '에게',
 '에서',
 '여',
 '여기',
 '여덟',
 '여러분',
 '여보시오',
 '여부',
 '여섯',
 ...]

In [255]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words = 'english')
tfidf = TfidfVectorizer(stop_words = stopwords_kor)
##### TfidfVectorizer 객체 tfidf 생성

##### 피쳐 벡터화

In [272]:
import warnings
warnings.filterwarnings(action='ignore')
# book['overview']에는 존재하지 않지만, 직접 작성한 한글 불용어 사전 txt 파일에는 존재하는 단어에 대한 warning발생을 억제 
books = book
books = books.loc[0:30000].reset_index(drop=True)
tfidf_matrix = tfidf.fit_transform(books['overview'])
tfidf_matrix.shape
# 1,244,550개의 row에 2974473개의 column(단어)이 존재

(30001, 10000)

In [273]:
tfidf_matrix
# 38,665,426개의 0이 아닌 데이터가 존재
# 10000 / 22,994,951
# 5000 / 19,530,492
# 100 / 4,764,232

<30001x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 562862 stored elements in Compressed Sparse Row format>

##### 3. 단어 유사도 판단을 위해 코사인 유사도 사용(linear_kernel)

###### 코사인 유사도는 벡터의 크기보다는 방향(각도)가 중요함. 앞에서 우리는 TfidfVectorizer
###### 를 통해 정규화된 벡터를 뽑아냈으므로 두 벡터의 내적을 통해서 코사인 유사도를 손쉽게 
###### 도출해 낼 수 있다. 이를 위해 Scikit-learn에서 제공하는 코사인 유사도 함수인 
###### linear_kernel(cosine_similarity과 결과는 같지만 처리 속도가 보다 빠르므로 선택) 사용

In [274]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

MemoryError: Unable to allocate 1.38 GiB for an array with shape (185343651,) and data type float64

In [243]:
cosine_sim.shape

(10001, 10001)

In [ ]:
# row 수를 줄이는것이 관건임

#### 사용자가 원하는 도서의 서명  →  단행본_도서와 문화데이터를 합쳐서 해당 도서의 ISBN으로 문화데이터에 해당하는 도서의 이름 출력